import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { SessionProvider } from "next-auth/react";
import ClientQueryProvider from "@/components/ClientQueryProvider";
import MainView from "./(Show)/_components/main-view/MainView";
import CollectionModal from "./(Show)/_components/main-view/Collection-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientQueryProvider>
    <SessionProvider>
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <MainView/>
        <CollectionModal/>
        {children}
      </body>
    </html>
    </SessionProvider>
    </ClientQueryProvider>
  );
}
